apiVersion: v1
kind: Pod
metadata:
  name: docker-react-pod
  labels: 
    component: web
spec:
  containers:
    - name: docker-react-app
      image: dashsaurabh/progressive-coder
      imagePullPolicy: Always
      ports: 
      - containerPort: 3000
